<?php

namespace AppBundle\Repository;

/**
 * UserAppliedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserAppliedRepository extends \Doctrine\ORM\EntityRepository
{
}
