<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;

/**
 * UserAppliedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserAppliedRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllForUserJobs(User $user)
    {
        $qb = $this->createQueryBuilder('favorite');

        return $qb->innerJoin('favorite.job', 'job')
            ->andWhere('favorite.user = :user')
            ->andWhere('job.isPublished = 1')
            ->orderBy('favorite.created', 'DESC')
            ->orderBy('favorite.id', 'DESC')
            ->setParameter('user', $user)
            ->getQuery()
            ->execute();
    }






}
