<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;

/**
 * UserAppliedRealRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserAppliedRealRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllForUserReality(User $user)
    {
        $qb = $this->createQueryBuilder('favorite');

        return $qb->innerJoin('favorite.reality', 'reality')
            ->andWhere('favorite.user = :user')
            ->andWhere('reality.realApplied = true')
            ->orderBy('favorite.created', 'DESC')
            ->orderBy('favorite.id', 'DESC')
            ->setParameter('user', $user)
            ->getQuery()
            ->execute();
    }
}
