#security:
#    encoders:
#        EmpBundle\Entity\Employee: bcrypt
#
#
#
##    role_hierarchy:
##        ROLE_USER:       ROLE_USER
##        ROLE_EMPLOYEE:  ROLE_ADMIN
##        ROLE_SUPER_ADMIN: ROLE_SUPER_ADMIN
#
#    providers:
#
#        employee:
#            entity:
#
#                class: EmpBundle:Employee
#                property: username
#
#    firewalls:
##        dev:
##            pattern: ^/(_(profiler|wdt)|css|images|js)/
##            security: false
#        employee:
#            pattern: ^/employee/
#            provider: employee
#
#
#            form_login:
##
#
#                login_path: security_login
#                check_path: security_login
#                default_target_path: employee_dash
#
#            logout_on_user_change: true
#
#            logout:
#                path:   logout
#                target: security_login
#
#            anonymous: ~
#
#
#
#
#    access_control:
#
##            - { path: ^/, role: ROLE_USER }
##            - { path: ^/employee/register, role: ROLE_SUPER_ADMIN }
##            - { path: ^/employee/dash, role: ROLE_EMPLOYEE }
##            - { path: ^/employee/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
##
#
#
#
#
#
#


security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
        EmpBundle\Entity\Employee: bcrypt


    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

        employee:
            entity:
                class: EmpBundle/Entity/Employee
                property: username

    firewalls:
        api:
            pattern: ^/api
            form_login:

                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                login_path: fos_user_security_login
                check_path: /api/login_check
                always_use_default_target_path: false
                default_target_path: /

                # if you are using Symfony < 2.8, use the following config instead:
#                 csrf_provider: form.csrf_provider

            logout_on_user_change: true
            logout:       true
            anonymous:    true

        employee:
            pattern: ^/employee/
            provider: employee


            form_login:
                login_path: security_login
                check_path: security_login
                default_target_path: employee_dash

            logout_on_user_change: true

            logout:
                path:   logout
                target: security_login

            anonymous: ~

    access_control:
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }