security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
        EmpBundle\Entity\Employee: bcrypt

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

        employee:
            entity:
                class: EmpBundle/Entity/Employee
                property: username

    firewalls:

        employee:
            pattern: ^/admin
            provider: employee

            form_login:
                login_path: security_login
                check_path: security_login
                username_parameter: _username
                password_parameter: _password
                default_target_path: employee_dash

            logout_on_user_change: true

            logout:
                path:   logout
                target: security_login

            anonymous: true

        register:
            pattern: ^/api/register
            anonymous: true
            stateless: true


        login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            form_login:
                check_path:               /api/login_check
                username_parameter: username
                password_parameter: password
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

        api:
            pattern:   ^/api
            stateless: true

            lexik_jwt: ~




        main:
            pattern: ^/

            form_login:
                login_path: /login
                check_path: /login_check
                default_target_path: /

            logout_on_user_change: true

            logout:
                path:   /logout
                target: /

            anonymous: true



#            guard:
#                authenticators:
#                    - lexik_jwt_authentication.jwt_token_authenticator




    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/api/v1/,       roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }