<?php

namespace EmpBundle\Repository;

/**
 * EdCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EdCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
