<?php

namespace EmpBundle\Repository;

/**
 * EduListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EduListRepository extends \Doctrine\ORM\EntityRepository
{
}
