<?php

namespace EmpBundle\Repository;

/**
 * FinCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FinCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
