<?php

namespace EmpBundle\Repository;

/**
 * FinListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FinListRepository extends \Doctrine\ORM\EntityRepository
{


}
