<?php

namespace EmpBundle\Repository;

/**
 * JobListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobListRepository extends \Doctrine\ORM\EntityRepository
{
}
