<?php

namespace EmpBundle\Repository;

/**
 * RealCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RealCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
