<?php

namespace EmpBundle\Repository;

/**
 * RealityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RealityRepository extends \Doctrine\ORM\EntityRepository
{
}
