<?php

namespace EmpBundle\Repository;

/**
 * RecruitmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecruitmentRepository extends \Doctrine\ORM\EntityRepository
{
}
