<?php

namespace EmpBundle\Repository;

/**
 * ReListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReListRepository extends \Doctrine\ORM\EntityRepository
{
}
